In [3]:
import sys
import sklearn
# Common imports
import numpy as np
import os

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import SGDRegressor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.linear_model import LogisticRegression

from sklearn import datasets

import warnings
warnings.filterwarnings("ignore")

def linear_closed_form(X, y):
    return np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)


#main program
if __name__ == '__main__':
    X = 2 * np.random.rand(100, 1) # normal distribution
    #print(X)
    y = 4 + 3 * X + np.random.randn(100, 1)
    #1을 생성
    b = np.ones((100, 1))
    theta = linear_closed_form(np.c_[b, X], y)
    print('closed form =', theta)


closed form = [[3.9247761 ]
 [3.12269045]]


In [7]:

    X1 = np.array([[0], [2]])
    X_new = np.c_[np.ones((2, 1)), X1]
    print(X_new)

    y_predict = X_new.dot(theta)
    print('closed predict = ', y_predict)


[[1. 0.]
 [1. 2.]]
closed predict =  [[ 3.9247761 ]
 [10.17015701]]


In [8]:
    lin_reg = LinearRegression()
    lin_reg.fit(X, y)
    print('linear reg = ', lin_reg.intercept_, lin_reg.coef_)
    y_predict = lin_reg.predict(X1)
    print('predict = ', y_predict)

    sgd_reg = SGDRegressor(max_iter=1000, tol=1e-3, penalty=None, eta0=0.1, random_state=42)

   

linear reg =  [3.9247761] [[3.12269045]]
predict =  [[ 3.9247761 ]
 [10.17015701]]


In [10]:
    print(y)
    # y가 차원이 2차원을 1차원으로
    print(y.ravel())
    sgd_reg.fit(X, y.ravel())
    print('SDG = ', sgd_reg.intercept_, sgd_reg.coef_)

[[ 7.3689877 ]
 [ 8.22729423]
 [ 8.26828523]
 [ 4.91208904]
 [10.62173678]
 [ 5.46442064]
 [ 7.79455275]
 [ 9.48785327]
 [ 7.25323754]
 [ 8.36766335]
 [ 7.64118355]
 [12.04941545]
 [10.90097858]
 [ 6.32783202]
 [ 3.68717592]
 [ 4.36419523]
 [ 8.62574052]
 [11.09000592]
 [ 9.2760866 ]
 [ 5.89210772]
 [ 9.3496376 ]
 [ 7.72492536]
 [ 4.2164917 ]
 [ 6.30905386]
 [ 6.01263851]
 [ 6.20152586]
 [ 9.63406519]
 [ 5.45109175]
 [ 9.38656154]
 [ 8.99986458]
 [11.81307558]
 [ 3.45721316]
 [ 3.99932943]
 [ 7.61625626]
 [ 3.34201277]
 [ 7.19076482]
 [ 8.41799281]
 [ 9.70627643]
 [ 9.20044357]
 [ 3.08133913]
 [ 6.57051328]
 [ 5.21878954]
 [ 9.59430101]
 [ 9.6522644 ]
 [ 9.3700172 ]
 [ 9.40790883]
 [ 7.57514246]
 [ 3.81785486]
 [ 5.1553782 ]
 [ 4.7111155 ]
 [ 8.83923937]
 [ 8.74999382]
 [ 5.77333223]
 [ 7.40661044]
 [ 4.5179952 ]
 [ 5.58803086]
 [ 5.30203207]
 [ 8.49826474]
 [ 6.08182721]
 [ 7.95869019]
 [ 9.4641846 ]
 [ 6.49274584]
 [ 8.95592911]
 [ 5.56307232]
 [ 7.88108081]
 [ 6.43153837]
 [ 7.83211

In [12]:
    y = 0.5 * X**2 + X + 2 + np.random.randn(m, 1)
    poly_features = PolynomialFeatures(degree=3, include_bias=False)
    X_poly = poly_features.fit_transform(X)
    print(X_poly)

[[-2.99569788e-01  8.97420580e-02 -2.68840093e-02]
 [ 1.32478498e+00  1.75505523e+00  2.32507081e+00]
 [-1.49280848e+00  2.22847715e+00 -3.32668958e+00]
 [-2.21025354e+00  4.88522073e+00 -1.07975764e+01]
 [-7.41871749e-01  5.50373692e-01 -4.08306694e-01]
 [-8.16940066e-01  6.67391071e-01 -5.45218505e-01]
 [ 1.38148259e+00  1.90849415e+00  2.63655145e+00]
 [ 2.46924148e-01  6.09715346e-02  1.50553442e-02]
 [-1.46907803e+00  2.15819025e+00 -3.17054987e+00]
 [ 2.82059226e+00  7.95574072e+00  2.24399007e+01]
 [ 2.61904400e+00  6.85939150e+00  1.79650482e+01]
 [ 2.45309187e+00  6.01765972e+00  1.47618721e+01]
 [ 2.26708417e+00  5.13967066e+00  1.16520660e+01]
 [-3.89763312e-01  1.51915439e-01 -5.92110648e-02]
 [ 1.38856526e+00  1.92811347e+00  2.67731138e+00]
 [-1.69651445e+00  2.87816128e+00 -4.88284220e+00]
 [-2.63665888e+00  6.95197003e+00 -1.83299735e+01]
 [ 2.18955253e+00  4.79414028e+00  1.04970220e+01]
 [ 2.05908152e-01  4.23981671e-02  8.73012825e-03]
 [-6.83536483e-01  4.67222124e-

In [11]:
    m = 100
    X = 6 * np.random.rand(m, 1) - 3
    print(X)

[[-0.29956979]
 [ 1.32478498]
 [-1.49280848]
 [-2.21025354]
 [-0.74187175]
 [-0.81694007]
 [ 1.38148259]
 [ 0.24692415]
 [-1.46907803]
 [ 2.82059226]
 [ 2.619044  ]
 [ 2.45309187]
 [ 2.26708417]
 [-0.38976331]
 [ 1.38856526]
 [-1.69651445]
 [-2.63665888]
 [ 2.18955253]
 [ 0.20590815]
 [-0.68353648]
 [ 1.11889644]
 [-0.03271851]
 [ 2.60125553]
 [ 2.27885876]
 [-2.2921616 ]
 [ 1.12360996]
 [-1.03176471]
 [ 0.19046448]
 [-0.9108331 ]
 [ 0.6468944 ]
 [-1.62786622]
 [ 0.93282733]
 [ 1.01259379]
 [-1.61154932]
 [ 0.8956161 ]
 [-2.94519447]
 [ 0.34450409]
 [ 1.45416029]
 [-2.71997708]
 [ 0.33941281]
 [ 0.33408813]
 [ 1.30105461]
 [ 0.71682153]
 [ 0.13344694]
 [-2.54444329]
 [-1.05142799]
 [-2.94831612]
 [-1.35125228]
 [ 0.84399294]
 [ 2.53977274]
 [-1.21306897]
 [ 1.89077853]
 [-0.3723634 ]
 [-2.84653787]
 [-2.30365518]
 [ 2.51513346]
 [-0.65648775]
 [ 2.22398579]
 [-0.67029409]
 [-0.16828853]
 [ 2.74255626]
 [-2.66876428]
 [-1.23987806]
 [ 1.33732903]
 [ 0.97418405]
 [ 0.08988871]
 [-1.16825

In [13]:
    lin_reg = LinearRegression()
    lin_reg.fit(X_poly, y)
    print('polynomial =', lin_reg.intercept_, lin_reg.coef_)
    X1_poly = poly_features.fit_transform(X1)
    y_predict = lin_reg.predict(X1_poly)
    print('predict = ', y_predict)

polynomial = [1.93149835] [[ 1.06532674  0.49766732 -0.02846876]]
predict =  [[1.93149835]
 [5.82507106]]


In [14]:

    # Regularized models

    np.random.seed(42)
    m = 20
    X = 3 * np.random.rand(m, 1)
    y = 1 + 0.5 * X + np.random.randn(m, 1) / 1.5 #노이즈를 살짝 줄임
    X_new = np.linspace(0, 3, 100).reshape(100, 1)


    ridge_reg = Ridge(alpha=1, solver="cholesky", random_state=42)
    ridge_reg.fit(X, y)
    y_predict = ridge_reg.predict([[1.5]])
    print('Ridge= ', y_predict)





Ridge=  [[1.55071465]]


In [15]:
    lasso_reg = Lasso(alpha=0.1)
    lasso_reg.fit(X, y)
    y_predict = lasso_reg.predict([[1.5]])
    print('Lasso = ', y_predict)



Lasso =  [1.53788174]


In [16]:
    elastic_net = ElasticNet(alpha=0.1, l1_ratio=0.5, random_state=42)
    elastic_net.fit(X, y)
    y_predict = elastic_net.predict([[1.5]])
    print('ElasticNet = ', y_predict)

ElasticNet =  [1.54333232]


In [17]:
    # Logistic regression
    iris = datasets.load_iris()
    print(list(iris.keys()))
    print(iris.DESCR)
    print(iris.data)
    print(iris.target)


['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module']
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:   

In [18]:

    # feature : sepal length / sepal width / petal length / petal width in cm
    # class : Iris-Setosa / Iris-Versicolour / Iris-Virginica
    X = iris["data"][:, 3:]  # petal width
    y = (iris["target"] == 2).astype(np.int)  # 1 if Iris virginica, else 0
    print(X)
    print(y)

[[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.4]
 [0.3]
 [0.2]
 [0.2]
 [0.1]
 [0.2]
 [0.2]
 [0.1]
 [0.1]
 [0.2]
 [0.4]
 [0.4]
 [0.3]
 [0.3]
 [0.3]
 [0.2]
 [0.4]
 [0.2]
 [0.5]
 [0.2]
 [0.2]
 [0.4]
 [0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.4]
 [0.1]
 [0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.1]
 [0.2]
 [0.2]
 [0.3]
 [0.3]
 [0.2]
 [0.6]
 [0.4]
 [0.3]
 [0.2]
 [0.2]
 [0.2]
 [0.2]
 [1.4]
 [1.5]
 [1.5]
 [1.3]
 [1.5]
 [1.3]
 [1.6]
 [1. ]
 [1.3]
 [1.4]
 [1. ]
 [1.5]
 [1. ]
 [1.4]
 [1.3]
 [1.4]
 [1.5]
 [1. ]
 [1.5]
 [1.1]
 [1.8]
 [1.3]
 [1.5]
 [1.2]
 [1.3]
 [1.4]
 [1.4]
 [1.7]
 [1.5]
 [1. ]
 [1.1]
 [1. ]
 [1.2]
 [1.6]
 [1.5]
 [1.6]
 [1.5]
 [1.3]
 [1.3]
 [1.3]
 [1.2]
 [1.4]
 [1.2]
 [1. ]
 [1.3]
 [1.2]
 [1.3]
 [1.3]
 [1.1]
 [1.3]
 [2.5]
 [1.9]
 [2.1]
 [1.8]
 [2.2]
 [2.1]
 [1.7]
 [1.8]
 [1.8]
 [2.5]
 [2. ]
 [1.9]
 [2.1]
 [2. ]
 [2.4]
 [2.3]
 [1.8]
 [2.2]
 [2.3]
 [1.5]
 [2.3]
 [2. ]
 [2. ]
 [1.8]
 [2.1]
 [1.8]
 [1.8]
 [1.8]
 [2.1]
 [1.6]
 [1.9]
 [2. ]
 [2.2]
 [1.5]
 [1.4]
 [2.3]
 [2.4]
 [1.8]
 [1.8]
 [2.1]
 [2.4]
 [2.3]
 [1.9]

In [19]:

    log_reg = LogisticRegression(solver="lbfgs", random_state=42)
    log_reg.fit(X, y)
    
    X_new = np.linspace(0, 3, 1000).reshape(-1, 1)
    y_proba = log_reg.predict_proba(X_new)
    print('logit = ', y_proba)

    print(y_proba[:, 1] >= 0.5)
    decision_boundary = X_new[y_proba[:, 1] >= 0.5][0]
    print("decition boundary = ", decision_boundary)

    y_predict = log_reg.predict([[1.7], [1.5]])
    print('logit = ', y_predict)


    X = iris["data"]  # petal length, petal width
    y = iris["target"]

    softmax_reg = LogisticRegression(multi_class="multinomial",
                                     solver="lbfgs", C=10, random_state=42)
    softmax_reg.fit(X, y)
    X_new = [[5, 2, 1, 4], [2, 3, 4, 1]]
    y_proba = softmax_reg.predict_proba(X_new)
    print('prob = ', y_proba)
    y_predict = softmax_reg.predict(X_new)
    print('predict = ', y_predict)
    

logit =  [[9.99250016e-01 7.49984089e-04]
 [9.99240201e-01 7.59799387e-04]
 [9.99230257e-01 7.69743043e-04]
 ...
 [3.08374822e-03 9.96916252e-01]
 [3.04400296e-03 9.96955997e-01]
 [3.00476842e-03 9.96995232e-01]]
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False Fa