In [2]:
def quicksort(arr):
    if len(arr) <=1:
        return arr
    pivot = arr[len(arr)//2]
    left = [x for x in arr if x<pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x>pivot]
    return quicksort(left) + middle + quicksort(right)

array = [3,6,8,10,1,2,1]
print(quicksort(array))

[1, 1, 2, 3, 6, 8, 10]


In [8]:
x = 3
print(type(x))
print(x)
print(x+1)
print(x-1)
print(x*2)
print(x**2)
x+=1
print(x)
x *= 2
print(x)
y=2.5
print(type(y))
print(y, y+1, y*2, y**2)

<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
2.5 3.5 5.0 6.25


In [10]:
t = True
f = False
print(type(t))
print(t and f)
print(t or f)
print(not t)
print(t !=f)

<class 'bool'>
False
True
False
True


In [12]:
hello="hello"
world='world'
print(hello)
print(len(hello))
hw = hello + ' ' + world
print(hw)
hw12 = '%s %s %d' %(hello, world, 12)
print(hw12)

hello
5
hello world
hello world 12


In [26]:
s = "hello"
print(s.capitalize())
print(s.upper())
print(s)
print(s.lower())
print(s.rjust(7))
print(s.center(7))
print(s.ljust(7))
print(s.replace('l', '(changed)'))
print('   world'.strip())
s1 = "maker's mark"
s1 = s1.replace('m', '(changed)')
print(s1)

Hello
HELLO
hello
hello
  hello
 hello 
hello  
he(changed)(changed)o
world
(changed)aker's (changed)ark


In [36]:
nums = list(range(5))
print(nums)
print(nums[2:4])
print(nums[2:])
print(nums[:2])
print(nums[:])
print(nums[:-1])
print(nums[-1])
nums[2:4] = [8, 9]
print(nums)
print(nums[:-1])

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
4
[0, 1, 8, 9, 4]
[0, 1, 8, 9]


In [39]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)

cat
dog
monkey


In [41]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d번째: %s' %(idx+1, animal))

#1번째: cat
#2번째: dog
#3번째: monkey


In [48]:
arr = list(range(10))
for i in arr:
    arr[i] +=10

for i, num in enumerate(arr):
    print(f"{i}번째 배열은 {num}입니다.")


0번째 배열은 10입니다.
1번째 배열은 11입니다.
2번째 배열은 12입니다.
3번째 배열은 13입니다.
4번째 배열은 14입니다.
5번째 배열은 15입니다.
6번째 배열은 16입니다.
7번째 배열은 17입니다.
8번째 배열은 18입니다.
9번째 배열은 19입니다.


In [51]:
import numpy as np
a = [[1,2,3], [4,5,6]]
matrix = np.array(a)
for r, row in enumerate(matrix):
    for c, letter in enumerate(row):
        print(f"{r}행 {c}열: {matrix}");

0행 0열: [[1 2 3]
 [4 5 6]]
0행 1열: [[1 2 3]
 [4 5 6]]
0행 2열: [[1 2 3]
 [4 5 6]]
1행 0열: [[1 2 3]
 [4 5 6]]
1행 1열: [[1 2 3]
 [4 5 6]]
1행 2열: [[1 2 3]
 [4 5 6]]


In [59]:
matrix1 = [['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]
for i in range(len(matrix1)):
    for j in range(len(matrix1[i])):
        print(i, j, matrix1[i][j])

0 0 A
0 1 B
0 2 C
1 0 D
1 1 E
1 2 F
2 0 G
2 1 H
2 2 I


In [66]:
for i, row in enumerate(matrix1):
    for j, letter in enumerate(row):
        print(f"{i}번째 행, {j}번쨰 열: {letter}")

0번째 행, 0번쨰 열: A
0번째 행, 1번쨰 열: B
0번째 행, 2번쨰 열: C
1번째 행, 0번쨰 열: D
1번째 행, 1번쨰 열: E
1번째 행, 2번쨰 열: F
2번째 행, 0번쨰 열: G
2번째 행, 1번쨰 열: H
2번째 행, 2번쨰 열: I


In [67]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x**2)
print(squares)

[0, 1, 4, 9, 16]


In [71]:
nums = [0,1,2,3,4]
even_squares = []
even_squares = [((x**2)) for x in nums if x%2==0]
print(even_squares)

[0, 4, 16]


In [84]:
d = {'cat':'cute', 'dog':'furry'}
print(d['cat'])
print('cat' in d)
d['fish'] = 'wet'
print(d['fish'])

print(d.get('monkey','N/A'))
print(d.get('fish', 'N/A'))
del d['fish']
print(d.get('fish', 'N/A'))

cute
True
wet
N/A
wet
N/A


In [88]:
d = {'person':2, 'cat':4, 'spider':8}
for animal in d:
    number_of_legs = d[animal]
    print(f'A {animal} has {number_of_legs} legs')

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


In [92]:
nums=[0,1,2,3,4]
even_num_to_square = {x:x**2 for x in nums if x>=0}
print(even_num_to_square)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}


In [99]:
animals = {'cat', 'dog'}
print('cat' in animals)
print('fish' in animals)
animals.add('fish')
print('fish' in animals)
print(len(animals))
animals.add('cat')
print(len(animals))
animals.remove('cat')
print(len(animals))

True
False
True
3
3
2


In [103]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print(f"{idx}번째는 {animal}")

0번째는 fish
1번째는 dog
2번째는 cat


In [104]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print(nums)

{0, 1, 2, 3, 4, 5}


In [106]:
d = {(x, x+1):x for x in range(10)}
t = (5, 6)
print(type(t))
print(d[t])
print(d[(1,2)])

<class 'tuple'>
5
1


In [107]:
def sign(x):
    if x>0:
        return 'positive'
    elif x==0:
        return 'zero'
    else:
        return 'negative'
    
for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


In [108]:
def hello(name, test=False):
    if test:
        print(f"HELLO, {name}!")
    else:
        print(f"hello, {name}")
        
hello('Bob')
hello('Fred', test=True)

hello, Bob
HELLO, Fred!


In [122]:
class Greeter(object):
    
    def __init__(self, name):
        self.name = name
        
    def greet(self, test=False):
        if test:
            print(f"HELLO, {self.name.upper()}")
        else:
            print(f"Hello, {self.name}")
            
g = Greeter('Fred')
g.greet()
g.greet(test=True)

Hello, Fred
HELLO, FRED


In [123]:
import numpy as np

In [130]:
a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

b = np.array([[1,2,3], [4,5,6]])
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [142]:
a = np.zeros((3,3))
print(a)

b = np.ones((3,2))
print(b)

c = np.full((4,4), 32)
print(c)

d = np.eye(3)
print(d)

e = np.random.random((2,2))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[32 32 32 32]
 [32 32 32 32]
 [32 32 32 32]
 [32 32 32 32]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.09863012 0.42033478]
 [0.8859994  0.28620709]]


In [161]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20], [21,22,23,24,25]])
print(a)

b=a[0:3, 0:3]
print(b)

print("---------------------")
print(a[0:3])
print(a[1,3])
print("---------------------")
b[0,0] = 77
print(b[0,0])

print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
---------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
9
---------------------
77
[[77  2  3]
 [ 6  7  8]
 [11 12 13]]


In [168]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

row_r1=a[0, :]
row_r2=a[1:3, :]
row_r3=a[0:1, :]
print(row_r1, row_r1.shape)
print(row_r3, row_r1.shape)
print("---------------------")
print(row_r2, row_r2.shape)
print("---------------------")
print("---------------------")
col_c1=a[:, 1]
col_c2=a[:, 1:2]
print(col_c1, col_c1.shape)

print(col_c2, col_c2.shape)

[1 2 3 4] (4,)
[[1 2 3 4]] (4,)
---------------------
[[ 5  6  7  8]
 [ 9 10 11 12]] (2, 4)
---------------------
---------------------
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [182]:
a=np.array([[1,2],[3,4],[5,6]])
print(a)
print("---------------------")
print(a[[0,1,2], [0,1,0]])
print(a[[0,1,2,], [1,1,1]])
print("---------------------")
print(np.array([a[0,0], a[1,1], a[2,0]]))
print(np.array([a[0,1], a[1,1], a[2,1]]))
print("---------------------")
print(a[[0,0], [1,1]])
print(a[[0,1], [1,1]])
print("---------------------")
print(np.array([a[0,1], a[0,1]]))

[[1 2]
 [3 4]
 [5 6]]
---------------------
[1 4 5]
[2 4 6]
---------------------
[1 4 5]
[2 4 6]
---------------------
[2 2]
[2 4]
---------------------
[2 2]


In [189]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)
print("---------------------")
b = np.array([0, 2, 0, 1])
print(b)
print("---------------------")
print(a[np.arange(4), b])
print("---------------------")
a[np.arange(4), b] += 100

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
---------------------
[0 2 0 1]
---------------------
[ 1  6  7 11]
---------------------
[[101   2   3]
 [  4   5 106]
 [107   8   9]
 [ 10 111  12]]


In [197]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12], [13,14,15]])
print(a)
b = np.array([0,1,2,0])
print(b)
print(a[np.arange(b.size), b])
a[np.arange(4), b] += 100
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[0 1 2 0]
[ 1  5  9 10]
[[101   2   3]
 [  4 105   6]
 [  7   8 109]
 [110  11  12]
 [ 13  14  15]]


In [201]:
a = np.array([[1,2], [3,4], [5,6]])

bool_idx = (a>2)
print(bool_idx)
print("---------------------")
print(a[bool_idx])
print(a[a<2])

[[False False]
 [ True  True]
 [ True  True]]
---------------------
[3 4 5 6]
[1]


In [205]:
x = np.array([1,2])
print(x.dtype)

x = np.array([1.0,2.0])
print(x.dtype)

x=np.array([1,2], dtype=np.int64)
print(x.dtype)

int32
float64
int64


In [209]:
x=np.array([[1,2], [3,4]], dtype=np.float64)
y=np.array([[5,6], [7,8]], dtype=np.float64)

print(x + y)
print(np.add(x,y))

print(x-y)
print(np.subtract(x,y))

print(x*y)
print(np.multiply(x,y))

print(x/y)
print(np.divide(x,y))

print(np.sqrt(x))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [213]:
x=np.array([[1,2], [3,4]])
y=np.array([[5,6], [7,8]])

v = np.array([9,10])
w = np.array([11,12])

print(v.dot(w))
print(np.dot(v,w))

print(x.dot(w))
print(np.dot(x,v))

print(x.dot(y))
print(np.dot(x,y))

219
219
[35 81]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [216]:
x=np.array([[1,2], [3,4]])

print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

10
[4 6]
[3 7]


In [220]:
x=np.array([[1,2], [3,4]])

x1 = x
print(x1)
x1=x1.T
print(x1)

v = np.array([[1,2,3], [4,5,6]])
print(v)
v = v.T
print(v)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
